# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Mikołaj Pipka
# title: 
email: mikolaj@pipka.eu
website: www.mikolaj.pipka.eu

# Social links
# twitter_username: facespics
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mikolaj.pipka.eu
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Jestem studentem Warszawskiego Uniwersytetu Medycznego. Posiadam doświadczenie w tworzeniu oraz adminsitracji stron internetowych. Wdrożyłem rozwiązania dla osób prywatnych, firm oraz instytucji publicznych. Interesuję się technologią w medycynie i telekomunikacją. Od ponad dekady zajmuję się fotagrafią.

  Najpewniej czuję się w: <mark>Wordpress</mark> oraz <mark>Fotografia prasowa</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Poza moimi zainteresowaniami w dziedzinie programowania, fotografii oraz telekomunikacji, uwielbiam również:
   - Kolarstwo
   - Podróże po Europie
   - Kawę


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
